# Generated by Django 4.1.6 on 2023-02-03 18:50
import json

from django.db import migrations


def load_from_json():
    with open(r'F:\moduls\modul-10\notes\noteapp\migrations\author.json', encoding="utf-8") as f:
        data = json.load(f)
        return data


def fill_authors(apps, schema_editor):
    author = apps.get_model("noteapp", "Author")
    data = load_from_json()
    for auth in data:
        author.full_name = auth["fullname"]
        author.born_date = auth["born_date"]
        author.born_location = auth["born_location"]
        author.description = auth["description"]
        author.save()


class Migration(migrations.Migration):
    dependencies = [
        ('noteapp', '0002_author_user_quote_user_tag_user_tag_tag of username'),
    ]

    operations = [
        migrations.RunPython(fill_authors)
    ]
