# Generated by Django 4.1.6 on 2023-02-03 19:53
import json

from django.db import migrations


def load_from_json():
    with open(r'F:\moduls\modul-10\notes\noteapp\migrations\author.json', encoding="utf-8") as f:
        data = json.load(f)
        return data


def fill_authors(apps, schema_editor):
    author = apps.get_model("noteapp", "Author")
    data = load_from_json()
    for auth in data:
        author.create(full_name=auth["fullname"],
                      born_date=auth["born_date"],
                      born_location=auth["born_location"],
                      description=auth["description"],
                      )


class Migration(migrations.Migration):
    dependencies = [
        ('noteapp', '0004_auto_20230203_2139'),
    ]

    operations = [
        migrations.RunPython(fill_authors)
    ]
