# Generated by Django 4.1.6 on 2023-02-03 20:11
import json

from django.db import migrations


def load_from_json():
    with open(r'F:\moduls\modul-10\notes\noteapp\migrations\quotes.json', encoding="utf-8") as f:
        data = json.load(f)
        return data


def fill_tags(apps, schema_editor):
    tag = apps.get_model("noteapp", "Tag")
    data = load_from_json()
    uniq_tags = []
    for quote in data:
        for t in quote["tags"]:
            if t not in uniq_tags:
                uniq_tags.append(t)
                tag.objects.create(name=t)




class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0006_auto_20230203_2157'),
    ]

    operations = [
    ]
