# Generated by Django 4.1.6 on 2023-02-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0007_auto_20230203_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
