# Generated by Django 4.1.6 on 2023-02-03 20:11
import json

from django.db import migrations


def load_from_json():
    with open(r'F:\moduls\modul-10\notes\noteapp\migrations\quotes.json', encoding="utf-8") as f:
        data = json.load(f)
        return data


def fill_quotes(apps, schema_editor):
    quote = apps.get_model("noteapp", "Quote")
    author = apps.get_model("noteapp", "Author")
    data = load_from_json()
    for q in data:
        author_id = author.objects.get(full_name=q["author"])
        quote.objects.create(author=author_id, quote=q["quote"])


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0009_auto_20230203_2226'),
    ]

    operations = [
        migrations.RunPython(fill_quotes)
    ]
